### ISSUE TITLE
Errors sending email on staging 0.3_alameda

### ISSUE THREAD

**Issue by pbn4** [bloom-housing/bloom#1038]
Corresponding unhandled exception from heroku staging: 
```
 <staging-no-reply@housingbayarea.org>... +158ms
2021-02-24T09:45:26.034872+00:00 app[web.1]: Error sending email to: michalp@airnauts.com! Error body: [object Object]
2021-02-24T09:45:26.040967+00:00 heroku[router]: at=info method=POST path="/applications/submit" host=hba-0-3-alameda-staging.herokuapp.com request_id=4c18d816-e7a5-4850-bb6e-d29338e6762c fwd="83.5.122.231" dyno=web.1 connect=0ms service=327ms status=201 bytes=4615 protocol=https
2021-02-24T09:45:26.041998+00:00 app[web.1]: (node:78) UnhandledPromiseRejectionWarning: Error: string expected for `html`
2021-02-24T09:45:26.042000+00:00 app[web.1]: at /app/node_modules/@sendgrid/helpers/classes/mail.js:634:15
2021-02-24T09:45:26.042001+00:00 app[web.1]: at /app/node_modules/@sendgrid/helpers/classes/mail.js:602:32
2021-02-24T09:45:26.042001+00:00 app[web.1]: at Array.some (<anonymous>)
2021-02-24T09:45:26.042002+00:00 app[web.1]: at Mail._checkProperty (/app/node_modules/@sendgrid/helpers/classes/mail.js:602:20)
2021-02-24T09:45:26.042002+00:00 app[web.1]: at Mail.addHtmlContent (/app/node_modules/@sendgrid/helpers/classes/mail.js:365:14)
2021-02-24T09:45:26.042003+00:00 app[web.1]: at Mail.fromData (/app/node_modules/@sendgrid/helpers/classes/mail.js:103:10)
2021-02-24T09:45:26.042003+00:00 app[web.1]: at new Mail (/app/node_modules/@sendgrid/helpers/classes/mail.js:46:12)
2021-02-24T09:45:26.042004+00:00 app[web.1]: at Function.create (/app/node_modules/@sendgrid/helpers/classes/mail.js:590:12)
2021-02-24T09:45:26.042004+00:00 app[web.1]: at MailService.send (/app/node_modules/@sendgrid/mail/src/classes/mail-service.js:194:25)
2021-02-24T09:45:26.042005+00:00 app[web.1]: at SendGridService.<anonymous> (/app/node_modules/@anchan828/nest-sendgrid/dist/sendgrid.service.js:50:31)
2021-02-24T09:45:26.042080+00:00 app[web.1]: (node:78) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)
```

**Comment by kathyccheng** [comment]
Looks like it's working now, closing
