### ISSUE TITLE
Redis timeout connection issue.

### ISSUE THREAD

**Issue by software-project** [bloom-housing/bloom#1271]
I have Redis env variables set and server running in the background but it can't connect and send a lot of exactly the same error to console:

```
 [ioredis] Unhandled error event: Error: connect ETIMEDOUT
 BACKEND_CORE     at TLSSocket.<anonymous> (/Users/martin/development/exygy/bloom/node_modules/ioredis/built/redis/index.js:308:37)
 BACKEND_CORE     at Object.onceWrapper (events.js:417:28)
 BACKEND_CORE     at TLSSocket.emit (events.js:311:20)
 BACKEND_CORE     at TLSSocket.Socket._onTimeout (net.js:478:8)
 BACKEND_CORE     at listOnTimeout (internal/timers.js:549:17)
 BACKEND_CORE     at processTimers (internal/timers.js:492:7)
```

My envs:
```
REDIS_TLS_URL=redis://127.0.0.1:6379/0
REDIS_URL=redis://127.0.0.1:6379/0
REDIS_USE_TLS=FALSE
```

**Comment by seanmalbert** [comment]
Hey @software-project ,
Taking your env environments, if I set `REDIS_USE_TLS=0` instead of FALSE, it connects for me. Does that work for you?

**Comment by software-project** [comment]
@seanmalbert that works. I suppose env sample was off, thank you. Closing
