### ISSUE TITLE
Application submission error

### ISSUE THREAD

**Issue by YazeedLoonat** [bloom-housing/bloom#3439]
We are currently getting the following error in paper trail

```
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466554044479&selected=1592982466554044479) [heroku/router](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aheroku%2Frouter&focus=1592982466554044479&selected=1592982466554044479) at=info method=POST path="/applications/submit" host=api.housingbayarea.org request_id=[09161fa4-f0a0-4c04-bcf4-c16f52b67ee3](https://my.papertrailapp.com/groups/25673261/events?q=%2209161fa4-f0a0-4c04-bcf4-c16f52b67ee3%22&focus=1592982466554044479&selected=1592982466554044479) fwd="[172.59.128.109](https://my.papertrailapp.com/groups/25673261/events?q=%22172.59.128.109%22&focus=1592982466554044479&selected=1592982466554044479), [10.1.86.55](https://my.papertrailapp.com/groups/25673261/events?q=%2210.1.86.55%22&focus=1592982466554044479&selected=1592982466554044479),[44.203.148.215](https://my.papertrailapp.com/groups/25673261/events?q=%2244.203.148.215%22&focus=1592982466554044479&selected=1592982466554044479)" dyno=web.2 connect=0ms service=10ms status=400 bytes=663 protocol=https
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735616&selected=1592982466634735616) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735616&selected=1592982466634735616) {
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735617&selected=1592982466634735617) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735617&selected=1592982466634735617)   message: [
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735618&selected=1592982466634735618) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735618&selected=1592982466634735618)     'householdExpectingChanges must be a boolean value',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735619&selected=1592982466634735619) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735619&selected=1592982466634735619)     'householdStudent must be a boolean value',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735620&selected=1592982466634735620) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735620&selected=1592982466634735620)     'incomeVouchers must be a boolean value',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735621&selected=1592982466634735621) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735621&selected=1592982466634735621)     'income must be shorter than or equal to 64 characters',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735622&selected=1592982466634735622) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735622&selected=1592982466634735622)     'income must be a string',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735623&selected=1592982466634735623) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735623&selected=1592982466634735623)     'incomePeriod must be one of the following values: perMonth, perYear'
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735624&selected=1592982466634735624) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735624&selected=1592982466634735624)   ],
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735625&selected=1592982466634735625) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735625&selected=1592982466634735625)   stack: 'BadRequestException: Bad Request Exception\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735626&selected=1592982466634735626) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735626&selected=1592982466634735626)     '    at ValidationPipe.exceptionFactory (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735627&selected=1592982466634735627) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735627&selected=1592982466634735627)     '    at ValidationPipe.transform (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735628&selected=1592982466634735628) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735628&selected=1592982466634735628)     '    at async resolveParamValue (/app/node_modules/@nestjs/core/router/router-execution-context.js:147:23)\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735629&selected=1592982466634735629) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735629&selected=1592982466634735629)     '    at async Promise.all (index 0)\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735630&selected=1592982466634735630) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735630&selected=1592982466634735630)     '    at async pipesFn (/app/node_modules/@nestjs/core/router/router-execution-context.js:150:13)\n' +
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735631&selected=1592982466634735631) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735631&selected=1592982466634735631)     '    at async /app/node_modules/@nestjs/core/router/router-execution-context.js:37:30',
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735632&selected=1592982466634735632) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735632&selected=1592982466634735632)   exception: BadRequestException: Bad Request Exception
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735633&selected=1592982466634735633) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735633&selected=1592982466634735633)       at ValidationPipe.exceptionFactory (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:90:20)
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735634&selected=1592982466634735634) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735634&selected=1592982466634735634)       at ValidationPipe.transform (/app/node_modules/@nestjs/common/pipes/validation.pipe.js:66:30)
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735635&selected=1592982466634735635) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735635&selected=1592982466634735635)       at async resolveParamValue (/app/node_modules/@nestjs/core/router/router-execution-context.js:147:23)
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735636&selected=1592982466634735636) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735636&selected=1592982466634735636)       at async Promise.all (index 0)
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735637&selected=1592982466634735637) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735637&selected=1592982466634735637)       at async pipesFn (/app/node_modules/@nestjs/core/router/router-execution-context.js:150:13)
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735638&selected=1592982466634735638) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735638&selected=1592982466634735638)       at async /app/node_modules/@nestjs/core/router/router-execution-context.js:37:30 {
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735639&selected=1592982466634735639) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735639&selected=1592982466634735639)     response: { statusCode: 400, message: [Array], error: 'Bad Request' },
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735640&selected=1592982466634735640) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735640&selected=1592982466634735640)     status: 400
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735641&selected=1592982466634735641) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735641&selected=1592982466634735641)   }
May 10 08:50:38 [hba-0-3-alameda-prod](https://my.papertrailapp.com/systems/hba-0-3-alameda-prod/events?focus=1592982466634735642&selected=1592982466634735642) [app/web.2](https://my.papertrailapp.com/groups/25673261/events?q=program%3Aapp%2Fweb.2&focus=1592982466634735642&selected=1592982466634735642) }

```

**QA NOTES** (can test on: https://bloom.exygy.dev/ )
go to public site and begin filling out an application for a listing 
after filling out 1-2 sections skip ahead by changing the url from something like: `/contact/name` to something like `/review/demographics` (the tail end of the url)
fill out the rest of the form till you get to the review application step. You should be able to verify data is missing, then click the confirm button. You should be given an error, only the edit button for the beginning of the form and the confirm button at the bottom should be disabled

on the flip side if the application is correct you should be able to submit the application correctly

**Comment by sarahlazarich** [comment]
@YazeedLoonat -- 

Error Message Text: 
- English: Your application is missing required fields. Please go back and correct this before submitting.
- Tagalog: Walang kinakailangang field ang iyong aplikasyon. Mangyaring bumalik at itama ito bago isumite.
- Spanish: A su solicitud le faltan campos obligatorios. Vuelva atrás y corrija esto antes de enviarlo.
- Vietnamese: Ứng dụng của bạn thiếu các trường bắt buộc. Vui lòng quay lại và sửa lỗi này trước khi gửi.
- Chinese: 您的申请缺少必填字段。请在提交前返回并更正此问题。
