### ISSUE TITLE
Unable to fetch applications by applicationId

### ISSUE THREAD

**Issue by dominikx96** [bloom-housing/bloom#892]
On the partners MVP we use `/applications GET` endpoint to fetch applications list per `listingID`.
Currently on the local environment, the backend returns:

BACKEND_CORE [Nest] 17278   - 12/07/2020, 17:05:06   [ExceptionsHandler] Cannot destructure property `city` of 'undefined' or 'null'. +76ms
BACKEND_CORE     at Object.exports.listingUrlSlug (/Users/dominikbarcikowski/Desktop/projekty/bloom/bloom/backend/core/dist/src/lib/url_helper.js:12:11)
BACKEND_CORE     at Listing.get urlSlug [as urlSlug] (/Users/dominikbarcikowski/Desktop/projekty/bloom/bloom/backend/core/dist/src/entity/listing.entity.js:58:29)

**Comment by dominikx96** [comment]
Approved & merged.
